import {
  SiReact, SiNextdotjs, SiNodedotjs, SiExpress, SiMongodb, SiMysql, SiPostgresql,
  SiFirebase, SiGit, SiGithub, SiJavascript, SiHtml5, SiCplusplus, SiC, SiPytorch,
} from 'react-icons/si'
import {
  Brain, Cloud, Wrench, Code2, MessageSquare, Terminal, Binary, Cpu,
  Bug, Lightbulb, Gauge, FileText, Database, Layers,
} from 'lucide-react'

export const SKILL_ICONS = {
  'C++': SiCplusplus,
  C: SiC,
  JavaScript: SiJavascript,
  'Data Structures': Binary,
  Algorithms: Layers,
  'Object-Oriented Programming': Code2,
  'Problem Solving': Lightbulb,
  Debugging: Bug,
  'Generative AI Fundamentals': Brain,
  'Machine Learning Fundamentals': Brain,
  'LLM Concepts': Brain,
  'AI Inference Concepts': Cpu,
  PyTorch: SiPytorch,
  'llama.cpp': Terminal,
  'LLM Quantization': Gauge,
  'Model Inference Optimization': Gauge,
  CUDA: Cpu,
  'GPU Computing': Cpu,
  'React.js': SiReact,
  'Next.js': SiNextdotjs,
  HTML5: SiHtml5,
  CSS3: Code2,
  'Node.js': SiNodedotjs,
  'Express.js': SiExpress,
  'REST APIs': Cloud,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  PostgreSQL: SiPostgresql,
  Firebase: SiFirebase,
  Git: SiGit,
  GitHub: SiGithub,
  'VS Code': Terminal,
  Postman: Wrench,
  'Claude AI': Brain,
  'Cursor AI': Wrench,
  ChatGPT: MessageSquare,
  'JWT Authentication': Cloud,
  CRUD: Database,
  Testing: Bug,
  'Performance Analysis': Gauge,
  'Technical Documentation': FileText,
}

export const SKILL_DESCRIPTIONS = {
  'C++': 'Systems programming foundation',
  C: 'Low-level programming fundamentals',
  JavaScript: 'ES6+ and application logic',
  'Data Structures': 'Core CS for efficient software',
  Algorithms: 'Problem-solving and complexity thinking',
  'Object-Oriented Programming': 'Modular software design',
  'Problem Solving': 'Analytical approach to software issues',
  Debugging: 'Identifying and resolving defects',
  'Generative AI Fundamentals': 'Foundational concepts — actively learning',
  'Machine Learning Fundamentals': 'Foundational concepts — actively learning',
  'LLM Concepts': 'Foundational concepts — actively learning',
  'AI Inference Concepts': 'Foundational concepts — actively learning',
  PyTorch: 'Currently exploring',
  'llama.cpp': 'Currently exploring',
  'LLM Quantization': 'Currently exploring',
  'Model Inference Optimization': 'Currently exploring',
  CUDA: 'Currently exploring',
  'GPU Computing': 'Currently exploring',
  'React.js': 'Component architecture and modern UI',
  'Next.js': 'Routing and production web apps',
  HTML5: 'Semantic markup and structure',
  CSS3: 'Responsive layouts and styling',
  'Node.js': 'Server-side JavaScript runtime',
  'Express.js': 'RESTful API development',
  'REST APIs': 'API design and integration',
  MySQL: 'Relational database design',
  MongoDB: 'Document-oriented data storage',
  PostgreSQL: 'Relational database systems',
  Firebase: 'Backend services and data integration',
  Git: 'Version control workflows',
  GitHub: 'Source management and collaboration',
  'VS Code': 'Development environment',
  Postman: 'API testing and documentation',
  'Claude AI': 'AI-assisted development workflow',
  'Cursor AI': 'AI-assisted coding workflow',
  ChatGPT: 'AI-assisted development workflow',
  'JWT Authentication': 'Token-based application auth',
  CRUD: 'Data operation patterns',
  Testing: 'Application validation and reliability',
  'Performance Analysis': 'Identifying performance issues',
  'Technical Documentation': 'Implementation notes and reports',
}

export function getGroupedSkills(skills) {
  return skills
}
